//go:build ignore

// gen.go writes table.go: the named character references of HTML, taken
// from the table golang.org/x/net/html carries in html/entity.go, which is
// the WHATWG list. Run it with go generate from the package directory.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func main() {
	dir, err := exec.Command("go", "list", "-m", "-f", "{{.Dir}}", "golang.org/x/net").Output()
	if err != nil {
		log.Fatal(err)
	}
	version, err := exec.Command("go", "list", "-m", "-f", "{{.Version}}", "golang.org/x/net").Output()
	if err != nil {
		log.Fatal(err)
	}
	path := filepath.Join(strings.TrimSpace(string(dir)), "html", "entity.go")
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		log.Fatal(err)
	}
	entries := map[string]string{}
	for _, d := range f.Decls {
		gd, ok := d.(*ast.GenDecl)
		if !ok || gd.Tok != token.VAR {
			continue
		}
		for _, s := range gd.Specs {
			vs := s.(*ast.ValueSpec)
			if len(vs.Names) != 1 || (vs.Names[0].Name != "entity" && vs.Names[0].Name != "entity2") {
				continue
			}
			for _, elt := range vs.Values[0].(*ast.CompositeLit).Elts {
				kv := elt.(*ast.KeyValueExpr)
				name, err := strconv.Unquote(kv.Key.(*ast.BasicLit).Value)
				if err != nil {
					log.Fatal(err)
				}
				var sb strings.Builder
				switch v := kv.Value.(type) {
				case *ast.BasicLit:
					sb.WriteRune(runeLit(v))
				case *ast.CompositeLit:
					for _, e := range v.Elts {
						sb.WriteRune(runeLit(e.(*ast.BasicLit)))
					}
				default:
					log.Fatalf("%s: unexpected value", name)
				}
				entries[name] = sb.String()
			}
		}
	}
	names := make([]string, 0, len(entries))
	maxLen, maxNoSemicolon := 0, 0
	for name := range entries {
		names = append(names, name)
		maxLen = max(maxLen, len(name))
		if !strings.HasSuffix(name, ";") {
			maxNoSemicolon = max(maxNoSemicolon, len(name))
		}
	}
	sort.Strings(names)
	var allNames, allValues strings.Builder
	nameOffsets := []int{0}
	valueOffsets := []int{0}
	for _, name := range names {
		allNames.WriteString(name)
		allValues.WriteString(entries[name])
		nameOffsets = append(nameOffsets, allNames.Len())
		valueOffsets = append(valueOffsets, allValues.Len())
	}
	if allNames.Len() > 0xFFFF || allValues.Len() > 0xFFFF {
		log.Fatal("the offsets no longer fit in uint16")
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by gen.go from golang.org/x/net/html@%s entity.go; DO NOT EDIT.\n\n", strings.TrimSpace(string(version)))
	b.WriteString("package htmlro\n\n")
	b.WriteString("// The named character references of HTML, each name with its semicolon\n")
	b.WriteString("// where the list has one, sorted by name for the binary search in\n")
	b.WriteString("// lookupEntity: entry i is the name entityNames[entityNameOffsets[i]:\n")
	b.WriteString("// entityNameOffsets[i+1]] and the value entityValues[entityValueOffsets[i]:\n")
	b.WriteString("// entityValueOffsets[i+1]]. Two strings and two offset arrays are a third\n")
	b.WriteString("// of the binary size of an array of string pairs.\n")
	fmt.Fprintf(&b, "const entityCount = %d\n\n", len(names))
	fmt.Fprintf(&b, "const entityNames = %q\n\n", allNames.String())
	fmt.Fprintf(&b, "const entityValues = %q\n\n", allValues.String())
	b.WriteString("var entityNameOffsets = [entityCount + 1]uint16{")
	for i, off := range nameOffsets {
		if i%16 == 0 {
			b.WriteString("\n\t")
		}
		fmt.Fprintf(&b, "%d, ", off)
	}
	b.WriteString("\n}\n\n")
	b.WriteString("var entityValueOffsets = [entityCount + 1]uint16{")
	for i, off := range valueOffsets {
		if i%16 == 0 {
			b.WriteString("\n\t")
		}
		fmt.Fprintf(&b, "%d, ", off)
	}
	b.WriteString("\n}\n\n")
	fmt.Fprintf(&b, "// maxEntityName is the longest name in entityTable, semicolon included.\nconst maxEntityName = %d\n\n", maxLen)
	fmt.Fprintf(&b, "// maxEntityWithoutSemicolon is the longest name in entityTable that has no\n// semicolon: the legacy references that are recognized without one.\nconst maxEntityWithoutSemicolon = %d\n", maxNoSemicolon)
	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("table.go", src, 0o644); err != nil {
		log.Fatal(err)
	}
}

func runeLit(l *ast.BasicLit) rune {
	r, _, tail, err := strconv.UnquoteChar(l.Value[1:len(l.Value)-1], '\'')
	if err != nil || tail != "" {
		log.Fatalf("%s: bad rune literal", l.Value)
	}
	return r
}
