// Code generated by tools/gen-simd-asm/gen.py; DO NOT EDIT.

//go:build !bdf_noconv && goexperiment.simd && go1.27 && !go1.28 && (amd64 || arm64) && !arm64 && !amd64.v2

package base

func Simd_f16x4_cvt_bits(a [2]uint64) int64            { return Simd_f16x4_cvt_bits_scalar(a) }
func Simd_f32x4_abs(a [2]uint64) [2]uint64             { return Simd_f32x4_abs_scalar(a) }
func Simd_f32x4_add(a, b [2]uint64) [2]uint64          { return Simd_f32x4_add_scalar(a, b) }
func Simd_f32x4_ceil(a [2]uint64) [2]uint64            { return Simd_f32x4_ceil_scalar(a) }
func Simd_f32x4_convert_i32x4_s(a [2]uint64) [2]uint64 { return Simd_f32x4_convert_i32x4_s_scalar(a) }
func Simd_f32x4_convert_i32x4_u(a [2]uint64) [2]uint64 { return Simd_f32x4_convert_i32x4_u_scalar(a) }
func Simd_f32x4_demote_f64x2_zero(a [2]uint64) [2]uint64 {
	return Simd_f32x4_demote_f64x2_zero_scalar(a)
}
func Simd_f32x4_div(a, b [2]uint64) [2]uint64 { return Simd_f32x4_div_scalar(a, b) }
func Simd_f32x4_eq(a, b [2]uint64) [2]uint64  { return Simd_f32x4_eq_scalar(a, b) }
func Simd_f32x4_extract_lane(v [2]uint64, lane int32) float32 {
	return Simd_f32x4_extract_lane_scalar(v, lane)
}
func Simd_f32x4_floor(a [2]uint64) [2]uint64   { return Simd_f32x4_floor_scalar(a) }
func Simd_f32x4_ge(a, b [2]uint64) [2]uint64   { return Simd_f32x4_ge_scalar(a, b) }
func Simd_f32x4_gt(a, b [2]uint64) [2]uint64   { return Simd_f32x4_gt_scalar(a, b) }
func Simd_f32x4_le(a, b [2]uint64) [2]uint64   { return Simd_f32x4_le_scalar(a, b) }
func Simd_f32x4_lt(a, b [2]uint64) [2]uint64   { return Simd_f32x4_lt_scalar(a, b) }
func Simd_f32x4_max(a, b [2]uint64) [2]uint64  { return Simd_f32x4_max_scalar(a, b) }
func Simd_f32x4_min(a, b [2]uint64) [2]uint64  { return Simd_f32x4_min_scalar(a, b) }
func Simd_f32x4_mul(a, b [2]uint64) [2]uint64  { return Simd_f32x4_mul_scalar(a, b) }
func Simd_f32x4_ne(a, b [2]uint64) [2]uint64   { return Simd_f32x4_ne_scalar(a, b) }
func Simd_f32x4_nearest(a [2]uint64) [2]uint64 { return Simd_f32x4_nearest_scalar(a) }
func Simd_f32x4_neg(a [2]uint64) [2]uint64     { return Simd_f32x4_neg_scalar(a) }
func Simd_f32x4_pmax(a, b [2]uint64) [2]uint64 { return Simd_f32x4_pmax_scalar(a, b) }
func Simd_f32x4_pmin(a, b [2]uint64) [2]uint64 { return Simd_f32x4_pmin_scalar(a, b) }
func Simd_f32x4_replace_lane(v [2]uint64, lane int32, x float32) [2]uint64 {
	return Simd_f32x4_replace_lane_scalar(v, lane, x)
}
func Simd_f32x4_splat(x float32) [2]uint64    { return Simd_f32x4_splat_scalar(x) }
func Simd_f32x4_sqrt(a [2]uint64) [2]uint64   { return Simd_f32x4_sqrt_scalar(a) }
func Simd_f32x4_sub(a, b [2]uint64) [2]uint64 { return Simd_f32x4_sub_scalar(a, b) }
func Simd_f32x4_trunc(a [2]uint64) [2]uint64  { return Simd_f32x4_trunc_scalar(a) }
func Simd_f64x2_abs(a [2]uint64) [2]uint64    { return Simd_f64x2_abs_scalar(a) }
func Simd_f64x2_add(a, b [2]uint64) [2]uint64 { return Simd_f64x2_add_scalar(a, b) }
func Simd_f64x2_ceil(a [2]uint64) [2]uint64   { return Simd_f64x2_ceil_scalar(a) }
func Simd_f64x2_convert_low_i32x4_s(a [2]uint64) [2]uint64 {
	return Simd_f64x2_convert_low_i32x4_s_scalar(a)
}
func Simd_f64x2_convert_low_i32x4_u(a [2]uint64) [2]uint64 {
	return Simd_f64x2_convert_low_i32x4_u_scalar(a)
}
func Simd_f64x2_div(a, b [2]uint64) [2]uint64 { return Simd_f64x2_div_scalar(a, b) }
func Simd_f64x2_eq(a, b [2]uint64) [2]uint64  { return Simd_f64x2_eq_scalar(a, b) }
func Simd_f64x2_extract_lane(v [2]uint64, lane int32) float64 {
	return Simd_f64x2_extract_lane_scalar(v, lane)
}
func Simd_f64x2_floor(a [2]uint64) [2]uint64   { return Simd_f64x2_floor_scalar(a) }
func Simd_f64x2_ge(a, b [2]uint64) [2]uint64   { return Simd_f64x2_ge_scalar(a, b) }
func Simd_f64x2_gt(a, b [2]uint64) [2]uint64   { return Simd_f64x2_gt_scalar(a, b) }
func Simd_f64x2_le(a, b [2]uint64) [2]uint64   { return Simd_f64x2_le_scalar(a, b) }
func Simd_f64x2_lt(a, b [2]uint64) [2]uint64   { return Simd_f64x2_lt_scalar(a, b) }
func Simd_f64x2_max(a, b [2]uint64) [2]uint64  { return Simd_f64x2_max_scalar(a, b) }
func Simd_f64x2_min(a, b [2]uint64) [2]uint64  { return Simd_f64x2_min_scalar(a, b) }
func Simd_f64x2_mul(a, b [2]uint64) [2]uint64  { return Simd_f64x2_mul_scalar(a, b) }
func Simd_f64x2_ne(a, b [2]uint64) [2]uint64   { return Simd_f64x2_ne_scalar(a, b) }
func Simd_f64x2_nearest(a [2]uint64) [2]uint64 { return Simd_f64x2_nearest_scalar(a) }
func Simd_f64x2_neg(a [2]uint64) [2]uint64     { return Simd_f64x2_neg_scalar(a) }
func Simd_f64x2_pmax(a, b [2]uint64) [2]uint64 { return Simd_f64x2_pmax_scalar(a, b) }
func Simd_f64x2_pmin(a, b [2]uint64) [2]uint64 { return Simd_f64x2_pmin_scalar(a, b) }
func Simd_f64x2_promote_low_f32x4(a [2]uint64) [2]uint64 {
	return Simd_f64x2_promote_low_f32x4_scalar(a)
}
func Simd_f64x2_replace_lane(v [2]uint64, lane int32, x float64) [2]uint64 {
	return Simd_f64x2_replace_lane_scalar(v, lane, x)
}
func Simd_f64x2_splat(x float64) [2]uint64          { return Simd_f64x2_splat_scalar(x) }
func Simd_f64x2_sqrt(a [2]uint64) [2]uint64         { return Simd_f64x2_sqrt_scalar(a) }
func Simd_f64x2_sub(a, b [2]uint64) [2]uint64       { return Simd_f64x2_sub_scalar(a, b) }
func Simd_f64x2_trunc(a [2]uint64) [2]uint64        { return Simd_f64x2_trunc_scalar(a) }
func Simd_i16x8_abs(a [2]uint64) [2]uint64          { return Simd_i16x8_abs_scalar(a) }
func Simd_i16x8_add(a, b [2]uint64) [2]uint64       { return Simd_i16x8_add_scalar(a, b) }
func Simd_i16x8_add_sat_s(a, b [2]uint64) [2]uint64 { return Simd_i16x8_add_sat_s_scalar(a, b) }
func Simd_i16x8_add_sat_u(a, b [2]uint64) [2]uint64 { return Simd_i16x8_add_sat_u_scalar(a, b) }
func Simd_i16x8_all_true(a [2]uint64) int32         { return Simd_i16x8_all_true_scalar(a) }
func Simd_i16x8_avgr_u(a, b [2]uint64) [2]uint64    { return Simd_i16x8_avgr_u_scalar(a, b) }
func Simd_i16x8_bitmask(a [2]uint64) int32          { return Simd_i16x8_bitmask_scalar(a) }
func Simd_i16x8_eq(a, b [2]uint64) [2]uint64        { return Simd_i16x8_eq_scalar(a, b) }
func Simd_i16x8_extadd_pairwise_i8x16_s(a [2]uint64) [2]uint64 {
	return Simd_i16x8_extadd_pairwise_i8x16_s_scalar(a)
}
func Simd_i16x8_extadd_pairwise_i8x16_u(a [2]uint64) [2]uint64 {
	return Simd_i16x8_extadd_pairwise_i8x16_u_scalar(a)
}
func Simd_i16x8_extend_high_i8x16_s(a [2]uint64) [2]uint64 {
	return Simd_i16x8_extend_high_i8x16_s_scalar(a)
}
func Simd_i16x8_extend_high_i8x16_u(a [2]uint64) [2]uint64 {
	return Simd_i16x8_extend_high_i8x16_u_scalar(a)
}
func Simd_i16x8_extend_low_i8x16_s(a [2]uint64) [2]uint64 {
	return Simd_i16x8_extend_low_i8x16_s_scalar(a)
}
func Simd_i16x8_extend_low_i8x16_u(a [2]uint64) [2]uint64 {
	return Simd_i16x8_extend_low_i8x16_u_scalar(a)
}
func Simd_i16x8_extmul_high_i8x16_s(a, b [2]uint64) [2]uint64 {
	return Simd_i16x8_extmul_high_i8x16_s_scalar(a, b)
}
func Simd_i16x8_extmul_high_i8x16_u(a, b [2]uint64) [2]uint64 {
	return Simd_i16x8_extmul_high_i8x16_u_scalar(a, b)
}
func Simd_i16x8_extmul_low_i8x16_s(a, b [2]uint64) [2]uint64 {
	return Simd_i16x8_extmul_low_i8x16_s_scalar(a, b)
}
func Simd_i16x8_extmul_low_i8x16_u(a, b [2]uint64) [2]uint64 {
	return Simd_i16x8_extmul_low_i8x16_u_scalar(a, b)
}
func Simd_i16x8_extract_lane_s(v [2]uint64, lane int32) int32 {
	return Simd_i16x8_extract_lane_s_scalar(v, lane)
}
func Simd_i16x8_extract_lane_u(v [2]uint64, lane int32) int32 {
	return Simd_i16x8_extract_lane_u_scalar(v, lane)
}
func Simd_i16x8_ge_s(a, b [2]uint64) [2]uint64  { return Simd_i16x8_ge_s_scalar(a, b) }
func Simd_i16x8_ge_u(a, b [2]uint64) [2]uint64  { return Simd_i16x8_ge_u_scalar(a, b) }
func Simd_i16x8_gt_s(a, b [2]uint64) [2]uint64  { return Simd_i16x8_gt_s_scalar(a, b) }
func Simd_i16x8_gt_u(a, b [2]uint64) [2]uint64  { return Simd_i16x8_gt_u_scalar(a, b) }
func Simd_i16x8_le_s(a, b [2]uint64) [2]uint64  { return Simd_i16x8_le_s_scalar(a, b) }
func Simd_i16x8_le_u(a, b [2]uint64) [2]uint64  { return Simd_i16x8_le_u_scalar(a, b) }
func Simd_i16x8_lt_s(a, b [2]uint64) [2]uint64  { return Simd_i16x8_lt_s_scalar(a, b) }
func Simd_i16x8_lt_u(a, b [2]uint64) [2]uint64  { return Simd_i16x8_lt_u_scalar(a, b) }
func Simd_i16x8_max_s(a, b [2]uint64) [2]uint64 { return Simd_i16x8_max_s_scalar(a, b) }
func Simd_i16x8_max_u(a, b [2]uint64) [2]uint64 { return Simd_i16x8_max_u_scalar(a, b) }
func Simd_i16x8_min_s(a, b [2]uint64) [2]uint64 { return Simd_i16x8_min_s_scalar(a, b) }
func Simd_i16x8_min_u(a, b [2]uint64) [2]uint64 { return Simd_i16x8_min_u_scalar(a, b) }
func Simd_i16x8_mul(a, b [2]uint64) [2]uint64   { return Simd_i16x8_mul_scalar(a, b) }
func Simd_i16x8_narrow_i32x4_s(a, b [2]uint64) [2]uint64 {
	return Simd_i16x8_narrow_i32x4_s_scalar(a, b)
}
func Simd_i16x8_narrow_i32x4_u(a, b [2]uint64) [2]uint64 {
	return Simd_i16x8_narrow_i32x4_u_scalar(a, b)
}
func Simd_i16x8_ne(a, b [2]uint64) [2]uint64            { return Simd_i16x8_ne_scalar(a, b) }
func Simd_i16x8_neg(a [2]uint64) [2]uint64              { return Simd_i16x8_neg_scalar(a) }
func Simd_i16x8_q15mulr_sat_s(a, b [2]uint64) [2]uint64 { return Simd_i16x8_q15mulr_sat_s_scalar(a, b) }
func Simd_i16x8_replace_lane(v [2]uint64, lane int32, x int32) [2]uint64 {
	return Simd_i16x8_replace_lane_scalar(v, lane, x)
}
func Simd_i16x8_shl(a [2]uint64, s int32) [2]uint64   { return Simd_i16x8_shl_scalar(a, s) }
func Simd_i16x8_shr_s(a [2]uint64, s int32) [2]uint64 { return Simd_i16x8_shr_s_scalar(a, s) }
func Simd_i16x8_shr_u(a [2]uint64, s int32) [2]uint64 { return Simd_i16x8_shr_u_scalar(a, s) }
func Simd_i16x8_splat(x int32) [2]uint64              { return Simd_i16x8_splat_scalar(x) }
func Simd_i16x8_sub(a, b [2]uint64) [2]uint64         { return Simd_i16x8_sub_scalar(a, b) }
func Simd_i16x8_sub_sat_s(a, b [2]uint64) [2]uint64   { return Simd_i16x8_sub_sat_s_scalar(a, b) }
func Simd_i16x8_sub_sat_u(a, b [2]uint64) [2]uint64   { return Simd_i16x8_sub_sat_u_scalar(a, b) }
func Simd_i32x4_abs(a [2]uint64) [2]uint64            { return Simd_i32x4_abs_scalar(a) }
func Simd_i32x4_add(a, b [2]uint64) [2]uint64         { return Simd_i32x4_add_scalar(a, b) }
func Simd_i32x4_all_true(a [2]uint64) int32           { return Simd_i32x4_all_true_scalar(a) }
func Simd_i32x4_bitmask(a [2]uint64) int32            { return Simd_i32x4_bitmask_scalar(a) }
func Simd_i32x4_dot_i16x8_s(a, b [2]uint64) [2]uint64 { return Simd_i32x4_dot_i16x8_s_scalar(a, b) }
func Simd_i32x4_eq(a, b [2]uint64) [2]uint64          { return Simd_i32x4_eq_scalar(a, b) }
func Simd_i32x4_extadd_pairwise_i16x8_s(a [2]uint64) [2]uint64 {
	return Simd_i32x4_extadd_pairwise_i16x8_s_scalar(a)
}
func Simd_i32x4_extadd_pairwise_i16x8_u(a [2]uint64) [2]uint64 {
	return Simd_i32x4_extadd_pairwise_i16x8_u_scalar(a)
}
func Simd_i32x4_extend_high_i16x8_s(a [2]uint64) [2]uint64 {
	return Simd_i32x4_extend_high_i16x8_s_scalar(a)
}
func Simd_i32x4_extend_high_i16x8_u(a [2]uint64) [2]uint64 {
	return Simd_i32x4_extend_high_i16x8_u_scalar(a)
}
func Simd_i32x4_extend_low_i16x8_s(a [2]uint64) [2]uint64 {
	return Simd_i32x4_extend_low_i16x8_s_scalar(a)
}
func Simd_i32x4_extend_low_i16x8_u(a [2]uint64) [2]uint64 {
	return Simd_i32x4_extend_low_i16x8_u_scalar(a)
}
func Simd_i32x4_extmul_high_i16x8_s(a, b [2]uint64) [2]uint64 {
	return Simd_i32x4_extmul_high_i16x8_s_scalar(a, b)
}
func Simd_i32x4_extmul_high_i16x8_u(a, b [2]uint64) [2]uint64 {
	return Simd_i32x4_extmul_high_i16x8_u_scalar(a, b)
}
func Simd_i32x4_extmul_low_i16x8_s(a, b [2]uint64) [2]uint64 {
	return Simd_i32x4_extmul_low_i16x8_s_scalar(a, b)
}
func Simd_i32x4_extmul_low_i16x8_u(a, b [2]uint64) [2]uint64 {
	return Simd_i32x4_extmul_low_i16x8_u_scalar(a, b)
}
func Simd_i32x4_extract_lane(v [2]uint64, lane int32) int32 {
	return Simd_i32x4_extract_lane_scalar(v, lane)
}
func Simd_i32x4_ge_s(a, b [2]uint64) [2]uint64  { return Simd_i32x4_ge_s_scalar(a, b) }
func Simd_i32x4_ge_u(a, b [2]uint64) [2]uint64  { return Simd_i32x4_ge_u_scalar(a, b) }
func Simd_i32x4_gt_s(a, b [2]uint64) [2]uint64  { return Simd_i32x4_gt_s_scalar(a, b) }
func Simd_i32x4_gt_u(a, b [2]uint64) [2]uint64  { return Simd_i32x4_gt_u_scalar(a, b) }
func Simd_i32x4_le_s(a, b [2]uint64) [2]uint64  { return Simd_i32x4_le_s_scalar(a, b) }
func Simd_i32x4_le_u(a, b [2]uint64) [2]uint64  { return Simd_i32x4_le_u_scalar(a, b) }
func Simd_i32x4_lt_s(a, b [2]uint64) [2]uint64  { return Simd_i32x4_lt_s_scalar(a, b) }
func Simd_i32x4_lt_u(a, b [2]uint64) [2]uint64  { return Simd_i32x4_lt_u_scalar(a, b) }
func Simd_i32x4_max_s(a, b [2]uint64) [2]uint64 { return Simd_i32x4_max_s_scalar(a, b) }
func Simd_i32x4_max_u(a, b [2]uint64) [2]uint64 { return Simd_i32x4_max_u_scalar(a, b) }
func Simd_i32x4_min_s(a, b [2]uint64) [2]uint64 { return Simd_i32x4_min_s_scalar(a, b) }
func Simd_i32x4_min_u(a, b [2]uint64) [2]uint64 { return Simd_i32x4_min_u_scalar(a, b) }
func Simd_i32x4_mul(a, b [2]uint64) [2]uint64   { return Simd_i32x4_mul_scalar(a, b) }
func Simd_i32x4_ne(a, b [2]uint64) [2]uint64    { return Simd_i32x4_ne_scalar(a, b) }
func Simd_i32x4_neg(a [2]uint64) [2]uint64      { return Simd_i32x4_neg_scalar(a) }
func Simd_i32x4_replace_lane(v [2]uint64, lane int32, x int32) [2]uint64 {
	return Simd_i32x4_replace_lane_scalar(v, lane, x)
}
func Simd_i32x4_shl(a [2]uint64, s int32) [2]uint64   { return Simd_i32x4_shl_scalar(a, s) }
func Simd_i32x4_shr_s(a [2]uint64, s int32) [2]uint64 { return Simd_i32x4_shr_s_scalar(a, s) }
func Simd_i32x4_shr_u(a [2]uint64, s int32) [2]uint64 { return Simd_i32x4_shr_u_scalar(a, s) }
func Simd_i32x4_splat(x int32) [2]uint64              { return Simd_i32x4_splat_scalar(x) }
func Simd_i32x4_sub(a, b [2]uint64) [2]uint64         { return Simd_i32x4_sub_scalar(a, b) }
func Simd_i32x4_trunc_sat_f32x4_s(a [2]uint64) [2]uint64 {
	return Simd_i32x4_trunc_sat_f32x4_s_scalar(a)
}
func Simd_i32x4_trunc_sat_f32x4_u(a [2]uint64) [2]uint64 {
	return Simd_i32x4_trunc_sat_f32x4_u_scalar(a)
}
func Simd_i32x4_trunc_sat_f64x2_s_zero(a [2]uint64) [2]uint64 {
	return Simd_i32x4_trunc_sat_f64x2_s_zero_scalar(a)
}
func Simd_i32x4_trunc_sat_f64x2_u_zero(a [2]uint64) [2]uint64 {
	return Simd_i32x4_trunc_sat_f64x2_u_zero_scalar(a)
}
func Simd_i64x2_abs(a [2]uint64) [2]uint64    { return Simd_i64x2_abs_scalar(a) }
func Simd_i64x2_add(a, b [2]uint64) [2]uint64 { return Simd_i64x2_add_scalar(a, b) }
func Simd_i64x2_all_true(a [2]uint64) int32   { return Simd_i64x2_all_true_scalar(a) }
func Simd_i64x2_bitmask(a [2]uint64) int32    { return Simd_i64x2_bitmask_scalar(a) }
func Simd_i64x2_eq(a, b [2]uint64) [2]uint64  { return Simd_i64x2_eq_scalar(a, b) }
func Simd_i64x2_extend_high_i32x4_s(a [2]uint64) [2]uint64 {
	return Simd_i64x2_extend_high_i32x4_s_scalar(a)
}
func Simd_i64x2_extend_high_i32x4_u(a [2]uint64) [2]uint64 {
	return Simd_i64x2_extend_high_i32x4_u_scalar(a)
}
func Simd_i64x2_extend_low_i32x4_s(a [2]uint64) [2]uint64 {
	return Simd_i64x2_extend_low_i32x4_s_scalar(a)
}
func Simd_i64x2_extend_low_i32x4_u(a [2]uint64) [2]uint64 {
	return Simd_i64x2_extend_low_i32x4_u_scalar(a)
}
func Simd_i64x2_extmul_high_i32x4_s(a, b [2]uint64) [2]uint64 {
	return Simd_i64x2_extmul_high_i32x4_s_scalar(a, b)
}
func Simd_i64x2_extmul_high_i32x4_u(a, b [2]uint64) [2]uint64 {
	return Simd_i64x2_extmul_high_i32x4_u_scalar(a, b)
}
func Simd_i64x2_extmul_low_i32x4_s(a, b [2]uint64) [2]uint64 {
	return Simd_i64x2_extmul_low_i32x4_s_scalar(a, b)
}
func Simd_i64x2_extmul_low_i32x4_u(a, b [2]uint64) [2]uint64 {
	return Simd_i64x2_extmul_low_i32x4_u_scalar(a, b)
}
func Simd_i64x2_extract_lane(v [2]uint64, lane int32) int64 {
	return Simd_i64x2_extract_lane_scalar(v, lane)
}
func Simd_i64x2_ge_s(a, b [2]uint64) [2]uint64 { return Simd_i64x2_ge_s_scalar(a, b) }
func Simd_i64x2_gt_s(a, b [2]uint64) [2]uint64 { return Simd_i64x2_gt_s_scalar(a, b) }
func Simd_i64x2_le_s(a, b [2]uint64) [2]uint64 { return Simd_i64x2_le_s_scalar(a, b) }
func Simd_i64x2_lt_s(a, b [2]uint64) [2]uint64 { return Simd_i64x2_lt_s_scalar(a, b) }
func Simd_i64x2_mul(a, b [2]uint64) [2]uint64  { return Simd_i64x2_mul_scalar(a, b) }
func Simd_i64x2_ne(a, b [2]uint64) [2]uint64   { return Simd_i64x2_ne_scalar(a, b) }
func Simd_i64x2_neg(a [2]uint64) [2]uint64     { return Simd_i64x2_neg_scalar(a) }
func Simd_i64x2_replace_lane(v [2]uint64, lane int32, x int64) [2]uint64 {
	return Simd_i64x2_replace_lane_scalar(v, lane, x)
}
func Simd_i64x2_shl(a [2]uint64, s int32) [2]uint64   { return Simd_i64x2_shl_scalar(a, s) }
func Simd_i64x2_shr_s(a [2]uint64, s int32) [2]uint64 { return Simd_i64x2_shr_s_scalar(a, s) }
func Simd_i64x2_shr_u(a [2]uint64, s int32) [2]uint64 { return Simd_i64x2_shr_u_scalar(a, s) }
func Simd_i64x2_splat(x int64) [2]uint64              { return Simd_i64x2_splat_scalar(x) }
func Simd_i64x2_sub(a, b [2]uint64) [2]uint64         { return Simd_i64x2_sub_scalar(a, b) }
func Simd_i8x16_abs(a [2]uint64) [2]uint64            { return Simd_i8x16_abs_scalar(a) }
func Simd_i8x16_add(a, b [2]uint64) [2]uint64         { return Simd_i8x16_add_scalar(a, b) }
func Simd_i8x16_add_sat_s(a, b [2]uint64) [2]uint64   { return Simd_i8x16_add_sat_s_scalar(a, b) }
func Simd_i8x16_add_sat_u(a, b [2]uint64) [2]uint64   { return Simd_i8x16_add_sat_u_scalar(a, b) }
func Simd_i8x16_all_true(a [2]uint64) int32           { return Simd_i8x16_all_true_scalar(a) }
func Simd_i8x16_avgr_u(a, b [2]uint64) [2]uint64      { return Simd_i8x16_avgr_u_scalar(a, b) }
func Simd_i8x16_bitmask(a [2]uint64) int32            { return Simd_i8x16_bitmask_scalar(a) }
func Simd_i8x16_eq(a, b [2]uint64) [2]uint64          { return Simd_i8x16_eq_scalar(a, b) }
func Simd_i8x16_extract_lane_s(v [2]uint64, lane int32) int32 {
	return Simd_i8x16_extract_lane_s_scalar(v, lane)
}
func Simd_i8x16_extract_lane_u(v [2]uint64, lane int32) int32 {
	return Simd_i8x16_extract_lane_u_scalar(v, lane)
}
func Simd_i8x16_ge_s(a, b [2]uint64) [2]uint64  { return Simd_i8x16_ge_s_scalar(a, b) }
func Simd_i8x16_ge_u(a, b [2]uint64) [2]uint64  { return Simd_i8x16_ge_u_scalar(a, b) }
func Simd_i8x16_gt_s(a, b [2]uint64) [2]uint64  { return Simd_i8x16_gt_s_scalar(a, b) }
func Simd_i8x16_gt_u(a, b [2]uint64) [2]uint64  { return Simd_i8x16_gt_u_scalar(a, b) }
func Simd_i8x16_le_s(a, b [2]uint64) [2]uint64  { return Simd_i8x16_le_s_scalar(a, b) }
func Simd_i8x16_le_u(a, b [2]uint64) [2]uint64  { return Simd_i8x16_le_u_scalar(a, b) }
func Simd_i8x16_lt_s(a, b [2]uint64) [2]uint64  { return Simd_i8x16_lt_s_scalar(a, b) }
func Simd_i8x16_lt_u(a, b [2]uint64) [2]uint64  { return Simd_i8x16_lt_u_scalar(a, b) }
func Simd_i8x16_max_s(a, b [2]uint64) [2]uint64 { return Simd_i8x16_max_s_scalar(a, b) }
func Simd_i8x16_max_u(a, b [2]uint64) [2]uint64 { return Simd_i8x16_max_u_scalar(a, b) }
func Simd_i8x16_min_s(a, b [2]uint64) [2]uint64 { return Simd_i8x16_min_s_scalar(a, b) }
func Simd_i8x16_min_u(a, b [2]uint64) [2]uint64 { return Simd_i8x16_min_u_scalar(a, b) }
func Simd_i8x16_narrow_i16x8_s(a, b [2]uint64) [2]uint64 {
	return Simd_i8x16_narrow_i16x8_s_scalar(a, b)
}
func Simd_i8x16_narrow_i16x8_u(a, b [2]uint64) [2]uint64 {
	return Simd_i8x16_narrow_i16x8_u_scalar(a, b)
}
func Simd_i8x16_ne(a, b [2]uint64) [2]uint64  { return Simd_i8x16_ne_scalar(a, b) }
func Simd_i8x16_neg(a [2]uint64) [2]uint64    { return Simd_i8x16_neg_scalar(a) }
func Simd_i8x16_popcnt(a [2]uint64) [2]uint64 { return Simd_i8x16_popcnt_scalar(a) }
func Simd_i8x16_replace_lane(v [2]uint64, lane int32, x int32) [2]uint64 {
	return Simd_i8x16_replace_lane_scalar(v, lane, x)
}
func Simd_i8x16_shl(a [2]uint64, s int32) [2]uint64    { return Simd_i8x16_shl_scalar(a, s) }
func Simd_i8x16_shr_s(a [2]uint64, s int32) [2]uint64  { return Simd_i8x16_shr_s_scalar(a, s) }
func Simd_i8x16_shr_u(a [2]uint64, s int32) [2]uint64  { return Simd_i8x16_shr_u_scalar(a, s) }
func Simd_i8x16_shuffle(a, b, pat [2]uint64) [2]uint64 { return Simd_i8x16_shuffle_scalar(a, b, pat) }
func Simd_i8x16_splat(x int32) [2]uint64               { return Simd_i8x16_splat_scalar(x) }
func Simd_i8x16_sub(a, b [2]uint64) [2]uint64          { return Simd_i8x16_sub_scalar(a, b) }
func Simd_i8x16_sub_sat_s(a, b [2]uint64) [2]uint64    { return Simd_i8x16_sub_sat_s_scalar(a, b) }
func Simd_i8x16_sub_sat_u(a, b [2]uint64) [2]uint64    { return Simd_i8x16_sub_sat_u_scalar(a, b) }
func Simd_i8x16_swizzle(a, s [2]uint64) [2]uint64      { return Simd_i8x16_swizzle_scalar(a, s) }
func Simd_v128_and(a, b [2]uint64) [2]uint64           { return Simd_v128_and_scalar(a, b) }
func Simd_v128_andnot(a, b [2]uint64) [2]uint64        { return Simd_v128_andnot_scalar(a, b) }
func Simd_v128_any_true(a [2]uint64) int32             { return Simd_v128_any_true_scalar(a) }
func Simd_v128_bitselect(a, b, c [2]uint64) [2]uint64  { return Simd_v128_bitselect_scalar(a, b, c) }
func Simd_v128_not(a [2]uint64) [2]uint64              { return Simd_v128_not_scalar(a) }
func Simd_v128_or(a, b [2]uint64) [2]uint64            { return Simd_v128_or_scalar(a, b) }
func Simd_v128_xor(a, b [2]uint64) [2]uint64           { return Simd_v128_xor_scalar(a, b) }
