package main

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// iconKeys are the keys of a palette style that make up an icon: its
// shape, icon, colors and outline (in the order they are written).
var iconKeys = []string{"shape", "resIcon", "grIcon", "grStroke", "fillColor", "gradientColor",
	"gradientDirection", "strokeColor", "fontColor", "dashed", "aspect"}

// groupKeys are the keys a group adds: those of a container and the
// placement of its label next to the group's icon.
var groupKeys = []string{"container", "collapsible", "recursiveResize", "pointerEvents",
	"verticalAlign", "align", "spacingLeft", "spacingTop"}

// fragment returns the style keys the target sets.
func (t *target) fragment() string {
	switch t.kind {
	case "builtin":
		return t.id
	case "groupicon":
		st := parseStyle(t.entry.style)
		return "shape=mxgraph.aws4." + t.id + ";fillColor=" + st["strokeColor"] +
			";gradientColor=none;strokeColor=none;fontColor=#232F3E;dashed=0;aspect=fixed"
	}
	keys := iconKeys
	if t.kind == "group" || t.kind == "rect" {
		keys = append(append([]string(nil), iconKeys...), groupKeys...)
	}
	st := parseStyle(t.entry.style)
	var parts []string
	for _, k := range keys {
		if v, ok := st[k]; ok {
			parts = append(parts, k+"="+v)
		}
	}
	return strings.Join(parts, ";")
}

// aspect returns the size whose aspect icons are fitted to, or 0, 0 for
// targets that keep the bounds.
func (t *target) aspect() (float64, float64) {
	switch t.kind {
	case "res":
		return 1, 1
	case "plain", "groupicon":
		if t.iconW > 0 && t.iconH > 0 {
			return t.iconW, t.iconH
		}
		return t.entry.w, t.entry.h
	}
	return 0, 0
}

// compareStyle returns the style of the target in a comparison sheet:
// the palette entry's style, or for overrides the old style with the
// fragment.
func (t *target) compareStyle(old string) string {
	switch t.kind {
	case "builtin":
		var parts []string
		for _, kv := range styleEntries(old) {
			if kv.key != "shape" {
				parts = append(parts, kv.key+"="+kv.value)
			}
		}
		return strings.Join(parts, ";") + ";" + t.fragment()
	case "groupicon":
		return t.fragment() + ";html=1;"
	}
	return t.entry.style
}

// writeTable returns the Go source of the table.
func writeTable(ds []decision) ([]byte, error) {
	sort.Slice(ds, func(i, j int) bool { return ds[i].name.name < ds[j].name.name })
	type key struct {
		style      string
		w, h       float64
		keepColors bool
	}
	index := map[key]int{}
	var targets []key
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by tools/gen-drawio-awsmap from draw.io %s; DO NOT EDIT.\n\n", release)
	b.WriteString("package drawio\n\n")
	var names bytes.Buffer
	for _, d := range ds {
		i := -1
		if t := d.target; t != nil {
			w, h := t.aspect()
			if w > 0 {
				w, h = round4(w), round4(h)
			}
			k := key{t.fragment(), w, h, t.kind == "builtin"}
			var ok bool
			if i, ok = index[k]; !ok {
				i = len(targets)
				index[k] = i
				targets = append(targets, k)
			}
		}
		fmt.Fprintf(&names, "\t%q: %d,\n", d.name.name, i)
	}
	b.WriteString("// awsLegacyTargets are the styles of the current AWS palette that the\n")
	b.WriteString("// shapes of older AWS generations are drawn with (see aws_legacy.go).\n")
	b.WriteString("var awsLegacyTargets = [...]awsLegacyTarget{\n")
	for _, t := range targets {
		fmt.Fprintf(&b, "\t{style: %q", t.style)
		if t.w > 0 {
			fmt.Fprintf(&b, ", w: %s, h: %s", fmtNum(t.w), fmtNum(t.h))
		}
		if t.keepColors {
			b.WriteString(", keepColors: true")
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("// awsLegacyShapes maps the shape names of older AWS generations to their\n")
	b.WriteString("// targets in awsLegacyTargets; -1 marks names without a counterpart.\n")
	b.WriteString("var awsLegacyShapes = map[string]int16{\n")
	b.Write(names.Bytes())
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}

func round4(v float64) float64 {
	f, _ := strconv.ParseFloat(strconv.FormatFloat(v, 'f', 4, 64), 64)
	return f
}

func fmtNum(v float64) string { return strconv.FormatFloat(v, 'f', -1, 64) }
