// Package cjkcmap holds Adobe's predefined CJK CMaps (the encodings of the
// Adobe-Japan1, -Japan2, -GB1, -CNS1 and -Korea1 character collections,
// such as 90ms-RKSJ-H or UniJIS-UCS2-H) and derives CID → Unicode for those
// collections from their UTF-32 CMaps.
//
// cmaps.bin.gz is generated by tools/gen-cmaps.py from Adobe's
// cmap-resources (BSD 3-Clause; see LICENSE in this directory).
package cjkcmap

import (
	"bytes"
	"compress/gzip"
	_ "embed"
	"encoding/binary"
	"errors"
	"io"
	"sort"
	"strings"
	"sync"
	"unicode/utf16"
	"unicode/utf8"
)

//go:embed cmaps.bin.gz
var data []byte

// Codespace is a code space range: codes of Bytes bytes from Lo to Hi.
type Codespace struct {
	Bytes  int
	Lo, Hi uint32
}

// CMap is a predefined CMap.
type CMap struct {
	Name       string
	Collection string // "Adobe-Japan1", …
	Vertical   bool   // WMode 1
	Codespace  []Codespace

	form   byte // how codes become keys: formCode, formUTF16, formUTF8
	ranges []rng
	base   *CMap // looked up (by key) after ranges
	parent *CMap // usecmap: looked up (by code) after base
}

type rng struct{ lo, hi, cid uint32 }

const (
	formCode  = 0
	formUTF16 = 1
	formUTF8  = 2
)

var (
	loadOnce sync.Once
	cmaps    map[string]*CMap
	loadErr  error
)

// Lookup returns the predefined CMap with the given name, or nil.
func Lookup(name string) *CMap {
	loadOnce.Do(load)
	return cmaps[name]
}

// CID returns the CID of a code, and false when the CMap does not map it.
func (m *CMap) CID(code uint32) (uint32, bool) { return m.cid(code, 0) }

// cid looks a code up in the ranges, then (as a key) in the base, then in
// the usecmap parent.
func (m *CMap) cid(code uint32, depth int) (uint32, bool) {
	if depth > 8 {
		return 0, false
	}
	key, ok := m.key(code)
	if !ok {
		return 0, false
	}
	if cid, ok := m.lookup(key); ok {
		return cid, true
	}
	if m.base != nil {
		if cid, ok := m.base.cid(key, depth+1); ok {
			return cid, true
		}
	}
	if m.parent != nil {
		return m.parent.cid(code, depth+1)
	}
	return 0, false
}

func (m *CMap) lookup(key uint32) (uint32, bool) {
	i := sort.Search(len(m.ranges), func(i int) bool { return m.ranges[i].hi >= key })
	if i < len(m.ranges) && m.ranges[i].lo <= key {
		r := m.ranges[i]
		return r.cid + key - r.lo, true
	}
	return 0, false
}

// key turns a code into the key the ranges use: a code point for the
// UCS-2, UTF-16 and UTF-8 CMaps (stored over their UTF-32 CMap).
func (m *CMap) key(code uint32) (uint32, bool) {
	switch m.form {
	case formUTF16:
		if code > 0xffff {
			r := utf16.DecodeRune(rune(code>>16), rune(code&0xffff))
			return uint32(r), r != utf8.RuneError
		}
		return code, code < 0xd800 || code > 0xdfff
	case formUTF8:
		var b [4]byte
		n := 1
		for c := code >> 8; c != 0; c >>= 8 {
			n++
		}
		if n > 4 {
			return 0, false
		}
		binary.BigEndian.PutUint32(b[:], code)
		r, size := utf8.DecodeRune(b[4-n:])
		return uint32(r), r != utf8.RuneError && size == n
	}
	return code, true
}

// CodePoint returns the Unicode character a code stands for in a Unicode
// CMap (UniJIS-UCS2-H, UniGB-UTF16-H, …); false for other CMaps.
func (m *CMap) CodePoint(code uint32) (rune, bool) {
	if !strings.HasPrefix(m.Name, "Uni") {
		return 0, false
	}
	if m.form == formCode {
		if !strings.Contains(m.Name, "-UTF32-") {
			// A Unicode CMap stored whole (UniJISPro-UCS2-V): decode UTF-16.
			k, ok := (&CMap{form: formUTF16}).key(code)
			return rune(k), ok
		}
		return rune(code), code <= utf8.MaxRune
	}
	k, ok := m.key(code)
	return rune(k), ok
}

func load() {
	cmaps = map[string]*CMap{}
	zr, err := gzip.NewReader(bytes.NewReader(data))
	if err != nil {
		loadErr = err
		return
	}
	raw, err := io.ReadAll(zr)
	if err != nil {
		loadErr = err
		return
	}
	if err := parse(raw); err != nil {
		loadErr = err
		cmaps = map[string]*CMap{}
	}
}

var errFormat = errors.New("cjkcmap: bad data")

func parse(b []byte) error {
	if !bytes.HasPrefix(b, []byte("BCM1")) {
		return errFormat
	}
	r := &reader{b: b, pos: 4}
	n := r.uvarint()
	links := map[*CMap][2]string{}
	for i := uint64(0); i < n && r.err == nil; i++ {
		m := &CMap{Name: r.str()}
		use := r.str()
		m.Collection = r.str()
		m.Vertical = r.u8() == 1
		m.form = r.u8()
		base := r.str()
		for k := r.uvarint(); k > 0 && r.err == nil; k-- {
			m.Codespace = append(m.Codespace, Codespace{Bytes: int(r.u8()), Lo: uint32(r.uvarint()), Hi: uint32(r.uvarint())})
		}
		k := r.uvarint()
		if k > uint64(len(b)) {
			return errFormat
		}
		m.ranges = make([]rng, 0, k)
		prevHi, nextCID := int64(-1), int64(0)
		for ; k > 0 && r.err == nil; k-- {
			lo := prevHi + 1 + int64(r.uvarint())
			hi := lo + int64(r.uvarint())
			cid := nextCID + r.varint()
			m.ranges = append(m.ranges, rng{uint32(lo), uint32(hi), uint32(cid)})
			prevHi, nextCID = hi, cid+hi-lo+1
		}
		cmaps[m.Name] = m
		links[m] = [2]string{base, use}
	}
	if r.err != nil {
		return r.err
	}
	for m, l := range links {
		m.base, m.parent = cmaps[l[0]], cmaps[l[1]]
		if len(m.Codespace) == 0 && m.parent != nil {
			m.Codespace = m.parent.Codespace
		}
	}
	return nil
}

type reader struct {
	b   []byte
	pos int
	err error
}

func (r *reader) u8() byte {
	if r.pos >= len(r.b) {
		r.err = errFormat
		return 0
	}
	r.pos++
	return r.b[r.pos-1]
}

func (r *reader) uvarint() uint64 {
	v, n := binary.Uvarint(r.b[min(r.pos, len(r.b)):])
	if n <= 0 {
		r.err = errFormat
		return 0
	}
	r.pos += n
	return v
}

func (r *reader) varint() int64 {
	u := r.uvarint()
	return int64(u>>1) ^ -int64(u&1)
}

func (r *reader) str() string {
	n := int(r.uvarint())
	if n < 0 || r.pos+n > len(r.b) {
		r.err = errFormat
		return ""
	}
	s := string(r.b[r.pos : r.pos+n])
	r.pos += n
	return s
}
