"""Generates converter/pdf/encodings.go and converter/pdf/glyphlist.go from fontTools data."""
import os
from fontTools import agl
from fontTools.encodings.StandardEncoding import StandardEncoding
from fontTools.encodings.MacRoman import MacRoman

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

def winansi():
    out = []
    for b in range(256):
        if b < 32:
            out.append(""); continue
        try:
            u = bytes([b]).decode("cp1252")
        except UnicodeDecodeError:
            out.append("bullet" if 0x80 <= b <= 0x9f else ""); continue  # unused codes show as bullet (Annex D note 3)
        if b == 0x7f: out.append(""); continue
        if b == 0xa0: out.append("space"); continue  # Annex D note 6
        if b == 0xad: out.append("hyphen"); continue # Annex D note 4
        out.append(agl.UV2AGL.get(ord(u), ""))
    out[0x27] = "quotesingle"; out[0x60] = "grave"
    return out

def fix(lst):
    return [("" if n == ".notdef" else n) for n in lst]

def golist(name, lst):
    lines = [f"var {name} = [256]string{{"]
    for i in range(0, 256, 8):
        lines.append("\t" + ", ".join(f'"{n}"' for n in lst[i:i+8]) + ",")
    lines.append("}")
    return "\n".join(lines)

with open(os.path.join(root, "converter/pdf/encodings.go"), "w") as f:
    f.write("// Code generated by test/pdf/gen_tables.py; DO NOT EDIT.\n\npackage pdf\n\n")
    f.write("// Predefined simple-font encodings (PDF 32000-1 Annex D): glyph name per code.\n\n")
    f.write(golist("standardEncoding", fix(StandardEncoding)) + "\n\n")
    f.write(golist("winAnsiEncoding", winansi()) + "\n\n")
    f.write(golist("macRomanEncoding", fix(MacRoman)) + "\n")

with open(os.path.join(root, "converter/pdf/glyphlist.go"), "w") as f:
    f.write("// Code generated by test/pdf/gen_tables.py; DO NOT EDIT.\n\npackage pdf\n\n")
    f.write("// glyphList maps Adobe Glyph List names to Unicode code points.\n")
    f.write("var glyphList = map[string]rune{\n")
    for n, uv in sorted(agl.AGL2UV.items()):
        f.write(f'\t"{n}": 0x{uv:04X},\n')
    f.write("}\n")
print("ok")
