package xlsx

import (
	"bytes"
	"compress/gzip"
	_ "embed"
	"io"
	"sync"

	"github.com/shibukawa/bdf"
	"github.com/shibukawa/bdf/converter/internal/ooxml"
)

// Tables (ListObjects, ECMA-376 Part 1 §18.5) format their cells with a
// table style: differential formats for the whole table, the header and
// total rows, the first and last columns and the stripes of rows and
// columns, applied in that order of precedence under the cells' own
// formats. The 60 built-in styles come from ECMA-376's
// presetTableStyles.xml (tablestyles.xml.gz, generated by
// tools/gen-tablestyles.py); workbooks define their own in the styles part.

//go:embed tablestyles.xml.gz
var tableStylesGz []byte

var (
	builtinOnce   sync.Once
	builtinStyles map[string]*ooxml.Node
)

func builtinTableStyle(name string) *ooxml.Node {
	builtinOnce.Do(func() {
		builtinStyles = map[string]*ooxml.Node{}
		zr, err := gzip.NewReader(bytes.NewReader(tableStylesGz))
		if err != nil {
			return
		}
		data, err := io.ReadAll(zr)
		if err != nil {
			return
		}
		root, err := ooxml.Parse(data)
		if err != nil {
			return
		}
		for _, s := range root.Children("style") {
			builtinStyles[s.AttrStr("name", "")] = s
		}
	})
	return builtinStyles[name]
}

// styleElem is a region of a table style with its format.
type styleElem struct {
	d    *dxf
	size int // stripe size
}

type table struct {
	ref                    cellRange
	header, totals         int
	firstCol, lastCol      bool
	rowStripes, colStripes bool
	elems                  map[string]styleElem
	filter                 bool
	filterButtons          map[int]bool // columns whose button is hidden
}

// loadTables reads the tables of the sheet.
func (s *sheetCtx) loadTables() {
	c := s.c
	for _, rid := range s.ws.tables {
		r, ok := c.pkg.Target(s.ws.part, rid)
		if !ok {
			continue
		}
		n, err := c.pkg.XML(r.Target)
		if err != nil {
			c.warnf("table %s: %v", r.Target, err)
			continue
		}
		ref, ok := parseRange(n.AttrStr("ref", ""))
		if !ok {
			continue
		}
		t := &table{ref: ref, header: int(n.AttrInt("headerRowCount", 1)), totals: int(n.AttrInt("totalsRowCount", 0)),
			elems: map[string]styleElem{}, filterButtons: map[int]bool{}}
		if t.totals == 0 && n.AttrBool("totalsRowShown", false) && n.AttrInt("totalsRowCount", -1) > 0 {
			t.totals = 1
		}
		if af := n.Child("autoFilter"); af != nil && t.header > 0 {
			t.filter = true
			for _, fc := range af.Children("filterColumn") {
				if fc.AttrBool("hiddenButton", false) || !fc.AttrBool("showButton", true) {
					t.filterButtons[int(fc.AttrInt("colId", 0))] = true
				}
			}
		}
		info := n.Child("tableStyleInfo")
		t.firstCol = info.AttrBool("showFirstColumn", false)
		t.lastCol = info.AttrBool("showLastColumn", false)
		t.rowStripes = info.AttrBool("showRowStripes", false)
		t.colStripes = info.AttrBool("showColumnStripes", false)
		if name := decodeXString(info.AttrStr("name", "")); name != "" {
			s.tableStyle(t, name)
		}
		s.tables = append(s.tables, t)
	}
}

// tableStyle resolves a table style by name: the workbook's own, or a
// built-in one.
func (s *sheetCtx) tableStyle(t *table, name string) {
	st := s.c.st
	if n, ok := st.tableStyle[name]; ok {
		for _, e := range n.Children("tableStyleElement") {
			id := int(e.AttrInt("dxfId", -1))
			if id < 0 || id >= len(st.dxfs) {
				continue
			}
			t.elems[e.AttrStr("type", "")] = styleElem{d: &st.dxfs[id], size: int(e.AttrInt("size", 1))}
		}
		return
	}
	b := builtinTableStyle(name)
	if b == nil {
		s.c.warnOnce("tablestyle:"+name, "table style %s is unknown", name)
		return
	}
	var dxfs []dxf
	for _, d := range b.Path("dxfs").Children("dxf") {
		dxfs = append(dxfs, st.parseDxf(d))
	}
	for _, e := range b.Path("tableStyles", "tableStyle").Children("tableStyleElement") {
		id := int(e.AttrInt("dxfId", 0)) - 1 // 1-based in the preset file
		if id < 0 || id >= len(dxfs) {
			continue
		}
		t.elems[e.AttrStr("type", "")] = styleElem{d: &dxfs[id], size: int(e.AttrInt("size", 1))}
	}
}

// tableAt returns the table a cell is in.
func (s *sheetCtx) tableAt(r, c int) *table {
	for _, t := range s.tables {
		if t.ref.contains(r, c) {
			return t
		}
	}
	return nil
}

func (t *table) isHeader(r int) bool { return r < t.ref.r0+t.header }

// region is a rectangle of the table that a style element covers.
type region struct {
	name string
	cellRange
}

// regions lists the style elements that cover a cell with their extents,
// lowest precedence first.
func (t *table) regions(r, c int) []region {
	ref := t.ref
	dataR0, dataR1 := ref.r0+t.header, ref.r1-t.totals
	var out []region
	add := func(name string, rg cellRange) {
		if _, ok := t.elems[name]; ok && rg.contains(r, c) {
			out = append(out, region{name, rg})
		}
	}
	add("wholeTable", ref)
	if t.colStripes && r >= dataR0 && r <= dataR1 {
		first, second := t.elems["firstColumnStripe"].size, t.elems["secondColumnStripe"].size
		first, second = max(first, 1), max(second, 1)
		off := (c - ref.c0) % (first + second)
		start := c - off
		if off < first {
			add("firstColumnStripe", cellRange{dataR0, start, dataR1, start + first - 1})
		} else {
			add("secondColumnStripe", cellRange{dataR0, start + first, dataR1, start + first + second - 1})
		}
	}
	if t.rowStripes && r >= dataR0 && r <= dataR1 {
		first, second := t.elems["firstRowStripe"].size, t.elems["secondRowStripe"].size
		first, second = max(first, 1), max(second, 1)
		off := (r - dataR0) % (first + second)
		start := r - off
		if off < first {
			add("firstRowStripe", cellRange{start, ref.c0, min(start+first-1, dataR1), ref.c1})
		} else {
			add("secondRowStripe", cellRange{start + first, ref.c0, min(start+first+second-1, dataR1), ref.c1})
		}
	}
	if t.lastCol {
		add("lastColumn", cellRange{ref.r0, ref.c1, ref.r1, ref.c1})
	}
	if t.firstCol {
		add("firstColumn", cellRange{ref.r0, ref.c0, ref.r1, ref.c0})
	}
	if t.header > 0 {
		add("headerRow", cellRange{ref.r0, ref.c0, ref.r0 + t.header - 1, ref.c1})
	}
	if t.totals > 0 {
		add("totalRow", cellRange{ref.r1 - t.totals + 1, ref.c0, ref.r1, ref.c1})
	}
	if t.header > 0 {
		if t.firstCol {
			add("firstHeaderCell", cellRange{ref.r0, ref.c0, ref.r0, ref.c0})
		}
		if t.lastCol {
			add("lastHeaderCell", cellRange{ref.r0, ref.c1, ref.r0, ref.c1})
		}
	}
	if t.totals > 0 {
		if t.firstCol {
			add("firstTotalCell", cellRange{ref.r1, ref.c0, ref.r1, ref.c0})
		}
		if t.lastCol {
			add("lastTotalCell", cellRange{ref.r1, ref.c1, ref.r1, ref.c1})
		}
	}
	return out
}

// apply lays the table style under a cell's own format: the fill when
// the cell has none, the font when the cell uses the default font, each
// border side the cell does not set. An element's outer borders go on the
// edges of its region, its inner (vertical, horizontal) ones between the
// cells inside.
func (t *table) apply(s *sheetCtx, f *cellFmt, r, c int) {
	var fill *xfill
	var font dxfFont
	var b xborder
	for _, rg := range t.regions(r, c) {
		d := t.elems[rg.name].d
		if d.fill != nil && !d.fill.empty() {
			fill = d.fill
		}
		if df := d.font; df != nil {
			if df.bold != nil {
				font.bold = df.bold
			}
			if df.italic != nil {
				font.italic = df.italic
			}
			if df.strike != nil {
				font.strike = df.strike
			}
			if df.underline != nil {
				font.underline = df.underline
			}
			if df.color.kind != colorNone {
				font.color = df.color
			}
		}
		if db := d.border; db != nil {
			side := func(dst *borderSide, outer, inner borderSide, isOuter bool) {
				src := inner
				if isOuter {
					src = outer
				}
				if src.style != "" {
					*dst = src
				}
			}
			side(&b.top, db.top, db.horizontal, r == rg.r0)
			side(&b.bottom, db.bottom, db.horizontal, r == rg.r1)
			side(&b.left, db.left, db.vertical, c == rg.c0)
			side(&b.right, db.right, db.vertical, c == rg.c1)
		}
	}
	if fill != nil && f.fill.empty() {
		f.fill = *fill
	}
	if f.fontID == 0 {
		if font.bold != nil {
			f.font.bold = *font.bold
		}
		if font.italic != nil {
			f.font.italic = *font.italic
		}
		if font.strike != nil {
			f.font.strike = *font.strike
		}
		if font.underline != nil {
			f.font.underline = *font.underline
		}
		if font.color.kind != colorNone {
			f.font.color = font.color
		}
	}
	for _, p := range []struct{ dst, src *borderSide }{{&f.border.top, &b.top}, {&f.border.bottom, &b.bottom}, {&f.border.left, &b.left}, {&f.border.right, &b.right}} {
		if p.dst.style == "" && p.src.style != "" {
			*p.dst = *p.src
		}
	}
}

// drawFilterButton draws the drop-down button of an AutoFilter at the
// right of a header cell.
func (s *sheetCtx) drawFilterButton(b box) {
	size := min(16*pxPt, b.h-pxPt, b.w)
	if size <= 2 {
		return
	}
	x, y := b.x+b.w-size-pxPt/2, b.y+b.h-size-pxPt/2
	for _, t := range s.tilesIn(x, y, x+size, y+size) {
		o := t.cv.Obj
		t.fillColor(bdf.RGB(0xf4, 0xf4, 0xf4))
		t.rect(x, y, size, size)
		o.Line(f32(pxPt), bdf.CapButt, bdf.JoinMiter, 10)
		o.StrokeColor(bdf.RGB(0xa6, 0xa6, 0xa6))
		o.StrokeRect(f32(x-t.ox+pxPt/2), f32(y-t.oy+pxPt/2), f32(size-pxPt), f32(size-pxPt))
		cx, cy, w := x+size/2-t.ox, y+size/2-t.oy, size*0.28
		p := &bdf.Path{}
		p.MoveTo(f32(cx-w), f32(cy-w/2)).LineTo(f32(cx+w), f32(cy-w/2)).LineTo(f32(cx), f32(cy+w/2)).Close()
		t.fillColor(bdf.RGB(0x40, 0x40, 0x40))
		o.FillPath(o.AddPath(p), 0)
	}
}
