#!/usr/bin/env python3
"""Generates converter/font/blocks.go from the Unicode Character Database's Blocks.txt.

Blocks.txt of the Unicode version Go's unicode package has (unicode.Version):
  https://www.unicode.org/Public/17.0.0/ucd/Blocks.txt
Usage: tools/gen-unicode-blocks.py Blocks.txt > converter/font/blocks.go
"""
import re
import sys

src = open(sys.argv[1], encoding="utf-8").read()
version = re.search(r"Blocks-([0-9.]+)\.txt", src).group(1)
print("// Code generated by tools/gen-unicode-blocks.py from Blocks-%s.txt; DO NOT EDIT." % version)
print()
print("package font")
print()
print("// blocks are the Unicode %s blocks: first and last code point, name." % version)
print("var blocks = []block{")
for line in src.splitlines():
    m = re.match(r"^([0-9A-F]+)\.\.([0-9A-F]+); (.+)$", line.strip())
    if m:
        print('\t{0x%s, 0x%s, "%s"},' % (m.group(1), m.group(2), m.group(3)))
print("}")
